plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - name: dev/*
    prerelease: '${name.replace(/^dev\//g, "dev-")}'
  - name: feature/*
    prerelease: '${name.replace(/^feature\//g, "feature-")}'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "hotfix-")}'
  - name: intern/*
    prerelease: '${name.replace(/^intern\//g, "intern-")}'
  - name: beta/*
    prerelease: true
  - name: next/*
    prerelease: '${name.replace(/^next\//g, "next-")}'
  - name: next-major/*
    prerelease: '${name.replace(/^next-major\//g, "next-major-")}'

