plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/github"

branches:
  - 0.0.1
  - main
  - name: dev/*
    prerelease: '${name.replace(/^dev\//g, "dev-")}'
  - name: feature/*
    prerelease: '${name.replace(/^feature\//g, "feature-")}'
  - name: hotfix/*
    prerelease: '${name.replace(/^hotfix\//g, "hotfix-")}'
  - name: intern/*
    prerelease: '${name.replace(/^intern\//g, "intern-")}'